### ISSUE TITLE
run command sync doesnt wait till command is fully finished

### ISSUE THREAD

**Issue by regevbr** [codeine-cd/codeine_node_utils#5]
Currently the run command sync waits till the command status states finished=true.
Sadly, in codeine, state finished doesn't mean that per nodes fail/success data still exists, causing the command to think it succeeded as there are no failing nodes.
Need to wait until command is finished and all the nodes reported their results

**Comment by ezraroi** [comment]
after checking the code it doesn't seems like this... Check `AllNodesCommandExecuter.execute()`
